services:
  api:
    image: ghcr.io/2024-2025-estia-bihar/final_projet_lucg:latest
    ports:
      - "8000:8000"
    volumes:
      - time_series_data:/app/data
      - model_registry:/app/model/registry

volumes:
  time_series_data:
  model_registry: